services:
  postgres:
    image: postgres:17
    container_name: dhaka-tesla-pool-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dhaka_tesla_pool

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server

    container_name: dhaka-tesla-pool-api
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dhaka_tesla_pool
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      NODE_ENV: production

    ports:
      - "5000:5000"

    depends_on:
      - postgres

  client:
    build:
      context: ./client

    container_name: dhaka-tesla-pool-client
    restart: unless-stopped

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api/v1

    ports:
      - "3000:3000"

    depends_on:
      - server

volumes:
  postgres_data:
